name: Auto PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to get full git history and branches

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.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 }}
          base: main
          branch: develop
          title: 'Auto PR: Merge develop → main'
          body: 'This PR was automatically created due to a push on `develop`.'
          draft: false
          delete-branch: false
