name: Auto PR from Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.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 }}
          base: main
          branch: develop
          title: 'Auto PR: Merge develop → main'
          body: 'This PR was automatically created due to a push on `develop`.'
          draft: false
          delete-branch: false
