name: Minimal PR Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create PR
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: develop
